# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "56005df7e3321c22b60cc081a067e495"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "bundlekit"

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
